name = "M27AI"
uid = "f27c55b4-v021-55b4-92b6-64398e75e23f"
version = 21 --REMINDER: Update M27Config to flag to remove ConExecute("WLD_GameSpeed 10"); Version reference in uid updated? Tested offline vs AI it should beat to check for any last minute errors introduced?
copyright = "FreeWare"
description = "Intended for 5x5 and to a lesser extent 10x10 1v1 maps. In relatively early stages of development but should be playable.  Report any bugs to maudlin27 (via forum or discord). See forum for details of changes by version.  Summary of recent focus areas: v19 - Rally points and air dominance strategy; v20 - experimentals and ACU; v21 - Eco management"
author = "maudlin27" --With thanks to Softles/Softlnoob for original Micro AI that was used as a starting point as I learned how to code AI
url = "https://forum.faforever.com/topic/2373/ai-development-guide-and-m27ai-v1-devlog"
icon = "/mods/M27AI/M27AI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
