---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 26/10/2021 07:21
---
--Manually turn below off prior to release
M27ShowUnitNames = false --(Overseer will set this to true if game settings are to show platoon names for all as well)
M27ShowEnemyUnitNames = false --Will rename enemy units to reflect their ID and lifetime count
M27RunVeryFast = false --Game starts off at +10 speed if set to adjustable
M27StrategicLog = false --Affects the strategic overseer logs which give various stats re the AI's state during the game
M27ShowPathingGraphically = false --(also turns on log showing map name) - Will draw the pathing for land, amphibious and navy if set to true, but will make things very slow

M27AllowDebugWithMultipleHumans = false --Some options like draw circle are disabled with >1 human in the game due to desync risk.  This can be used to enable them

--Profiling options:
M27StatTracking = false --Records data for all players, even if M27 isnt playing in the game
M27RunProfiling = false --Records data on how long most functions are taking; if setting to true part-way through game then need to also run ForkThread(M27Utilities.ProfilerActualTimePerTick)
M27ProfilingIgnoreFirst2Seconds = true --Means logic relating to pathing generation gets ignored
--M27ProfilingIgnoreFirstMin = true --Means logic relating to pathing generation gets ignored
M27RunSoftlesProfiling = false --Runs Softles profiling which tracks every function call (not just in my code but in the game) which allows calculation of the average tick length that a function occurs in (i.e. doesnt track time spent by each function but instead can use the correlation between function calls and how long a tick is taking)
M27RunGamePerformanceCheck = false --Runs regardless of whether M27 is active in the game, sends a log every second with how long it took to run that second and how many units are in the game.  Intended for August 2022 AI tourney performance profiling


--Randomness for alternative strategies
iLandSpamChance = 0.4 --from 0 to 1.0 (being 0 to 100% pre adjust; 0.4 means medium will be 40%, small 70%, very small 85%) - this is the value pre-weighting value, so will apply to medium sized maps; smaller maps will have an increased chance as a multiple of this - where certain conditions are satisfied to consider this strategy, then it will be adopted with this % chance subject to map modifiers; Current testing indicates land spam is marginally worse than normal approach (for M27)