---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 26/10/2021 07:21
---
--Manually turn below off prior to release
M27ShowUnitNames = true --(Overseer will set this to true if game settings are to show platoon names for all as well)
M27RunVeryFast = true --Game starts off at +10 speed if set to adjustable
M27StrategicLog = true --Affects the strategic overseer logs which give various stats re the AI's state during the game
M27ShowPathingGraphically = true --Will draw the pathing for land, amphibious and navy if set to true, but will make things very slow