---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 13/08/2022 18:01
---
local M27Events = import('/mods/M27AI/lua/AI/M27Events.lua')

local M27OldACUUnit = ACUUnit
ACUUnit = Class(M27OldACUUnit) {
    OnKilled = function(self, instigator, type, overkillRatio)
        M27Events.OnKilled(self, instigator, type, overkillRatio)
        M27OldACUUnit.OnKilled(self, instigator, type, overkillRatio)
    end,
    CreateEnhancement = function(self, enh)
        ForkThread(M27Events.OnEnhancementComplete, self, enh)
        return M27OldACUUnit.CreateEnhancement(self, enh)
    end
}