---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 21/11/2021 19:41
---
local M27Overseer = import('/mods/M27AI/lua/AI/M27Overseer.lua')

local M27OnCreateArmyBrain = OnCreateArmyBrain
function OnCreateArmyBrain(index, brain, name, nickname)
    local bDebugMessages = false
    local sFunctionRef = 'OnCreateArmyBrain'
    if bDebugMessages == true then LOG(sFunctionRef..': name='..name..'; nickname='..nickname..'; index='..index) end
    M27Overseer.AllAIBrainsBackup[index] = brain
    --M27Overseer.AnotherAIBrainsBackup[index] = brain
    --if bDebugMessages == true then LOG(sFunctionRef..': Size of AnotherAIBrainsBackup='..table.getn(M27Overseer.AnotherAIBrainsBackup)) end
    M27OnCreateArmyBrain(index, brain, name, nickname)
end