---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/08/2022 08:02
---

do --Per Balthazaar - encasing the code in do .... end means that you dont have to worry about using unique variables
    local M27OldProjectile = Projectile
    Projectile = Class(M27OldProjectile) {

        OnImpact = function(self, targetType, targetEntity)
            self.M27Impacted = true
            M27OldProjectile.OnImpact(self, targetType, targetEntity)
        end,
    }
end