---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 26/03/2022 18:45
---
local Entity = import('/lua/sim/Entity.lua').Entity
local M27Events = import('/mods/M27AI/lua/AI/M27Events.lua')

local M27OldProp = Prop
Prop = Class(M27OldProp) {
    Destroy = function(self)
        M27Events.OnPropDestroyed(self)
        M27OldProp.Destroy(self)
    end,
}