---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 05/08/2023 23:07
---
local M27Brain = import('/mods/M27AI/lua/AI/M27Brain.lua')
keyToBrain = keyToBrain or { }
keyToBrain["m27ai"] = M27Brain.NewAIBrain -- <- make sure import path points to the brain instance
keyToBrain["m27aicheat"] = M27Brain.NewAIBrain -- <- make sure import path points to the brain instance