---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 17/08/2022 19:03
---
local M27MapInfo = import('/mods/M27AI/lua/AI/M27MapInfo.lua')
local M27UnitInfo = import('/mods/M27AI/lua/AI/M27UnitInfo.lua')
local M27Utilities = import('/mods/M27AI/lua/M27Utilities.lua')

tPondDetails = {} --[a] = the naval pathing group; returns subtable of various information on ponds; Global information on ponds (requiring at least 200 space
subrefPondSize = 'PondSize'
subrefPondMinX = 'PondMinX'
subrefPondMinZ = 'PondMinZ'
subrefPondMaxX = 'PondMaxX'
subrefPondMaxZ = 'PondMaxZ'
subrefPondNearbyBrains = 'PondNearbyBrains'
subrefPondMexInfo = 'PondMexInfo'
subrefMexLocation = 'PondMexLocation'
subrefMexDistance = 'PondMexDistance'
subrefMexCanHitWithDF = 'PondMexDFDistance'
subrefMexCanHitWithIndirect = 'PondMexIndirectDistance'

function RecordPonds()
    --Call after recording all pathfinding for the map; intended to record key information on any ponds of interest
    local tiPondTempInfo = {}

    if M27MapInfo.bMapHasWater then
        --Record the size and dimensions of every pond
        for iX, tSubtable in M27MapInfo.tPathingSegmentGroupBySegment[M27UnitInfo.refPathingTypeNavy] do
            for iZ, iPathingGroup in tSubtable do
                if not(tPondDetails[iPathingGroup]) then
                    --Are we actually underwater?

                    tPondDetails[iPathingGroup] = {}
                    tPondDetails[iPathingGroup][subrefPondMinX] = 100000
                    tPondDetails[iPathingGroup][subrefPondMinZ] = 100000
                    tPondDetails[iPathingGroup][subrefPondMaxX] = 0
                    tPondDetails[iPathingGroup][subrefPondMaxZ] = 0
                    tPondDetails[iPathingGroup][subrefPondSize] = 0
                end
                tPondDetails[iPathingGroup][subrefPondSize] = tPondDetails[iPathingGroup][subrefPondSize] + 1
                tPondDetails[iPathingGroup][subrefPondMinX] = math.min(tPondDetails[iPathingGroup][subrefPondMinX], iX)
                tPondDetails[iPathingGroup][subrefPondMinZ] = math.min(tPondDetails[iPathingGroup][subrefPondMinZ], iZ)
                tPondDetails[iPathingGroup][subrefPondMaxX] = math.max(tPondDetails[iPathingGroup][subrefPondMaxX], iX)
                tPondDetails[iPathingGroup][subrefPondMaxZ] = math.max(tPondDetails[iPathingGroup][subrefPondMaxZ], iZ)
            end
        end
    end
end